2024-02-23 14:11:29,223 - INFO - [96mAttempting to grant permissions to needed files, for code to run correctly[0m
2024-02-23 14:11:29,223 - INFO - [96mExecuting grant_neccessary_permissions_sh_python3_files.sh script[0m
2024-02-23 14:11:29,223 - ERROR - Error: [Errno 13] Permission denied: './services_sh/grant_neccessary_permissions_sh_python3_files.sh'
2024-02-23 14:13:42,784 - INFO - [96mAttempting to grant permissions to needed files, for code to run correctly[0m
2024-02-23 14:13:42,784 - INFO - [96mExecuting grant_neccessary_permissions_sh_python3_files.sh script[0m
2024-02-23 14:13:42,787 - ERROR - Error: ./services_sh/grant_neccessary_permissions_sh_python3_files.sh: line 10: cd: ../services_python3: No such file or directory

2024-02-23 14:14:19,380 - INFO - [96mAttempting to grant permissions to needed files, for code to run correctly[0m
2024-02-23 14:14:19,380 - INFO - [96mExecuting grant_neccessary_permissions_sh_python3_files.sh script[0m
2024-02-23 14:14:19,382 - ERROR - Error: ./services_sh/grant_neccessary_permissions_sh_python3_files.sh: line 10: cd: ./services_python3: No such file or directory

2024-02-23 14:15:07,391 - INFO - [96mAttempting to grant permissions to needed files, for code to run correctly[0m
2024-02-23 14:15:07,391 - INFO - [96mExecuting grant_neccessary_permissions_sh_python3_files.sh script[0m
2024-02-23 14:15:07,393 - ERROR - Error: ./services_sh/grant_neccessary_permissions_sh_python3_files.sh: line 10: cd: ./services_python: No such file or directory

2024-02-23 14:15:44,558 - INFO - [96mAttempting to grant permissions to needed files, for code to run correctly[0m
2024-02-23 14:15:44,558 - INFO - [96mExecuting grant_neccessary_permissions_sh_python3_files.sh script[0m
2024-02-23 14:15:44,561 - INFO - [92mPermission granted to the needed files successfully.[0m
